config/routes.rb
Tourdefun::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :timeslots, only: [:show,:index], path: "schedule"
  resources :sponsors, only: :index

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :timeslot

  def self.this_year
    all.select do |artist|
      timeslot = artist.timeslot
      timeslot.this_year? if timeslot
    end
  end
end

app/models/page.rb
class Page < Petrie::Page
  include TheSortableTree::Scopes
  attr_accessor :subtitle

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  LEVELS = %w(platinum gold silver bronze)

  default_scope { order('position ASC') }

  scope :level, lambda { |level|
    where(level: LEVELS.index(level))
  }

  def self.level_from_index(i)
    LEVELS[i].capitalize if i
  end

  def self.levels_for_select
    (0...LEVELS.length).map { |i|
      [LEVELS[i].capitalize, i]
    }
  end

  def self.years_for_select
    (2010..Date.today.year + 1).to_a.reverse
  end

  def self.this_year
    where(year: Date.today.year)
  end

  def self.for_year(year)
    where(year: year)
  end

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  has_many :artists
  belongs_to :venue

  default_scope { order('start ASC') }
  scope :upcoming, -> {
    where("start >= ? AND published = ?", Date.today.beginning_of_year, true)
  }
  scope :this_year, -> {
    where(start: (Date.today.beginning_of_year..Date.today.end_of_year),
          published: true)
  }

  just_define_datetime_picker :start
  just_define_datetime_picker :end

  def self.first_show_time
    shows = upcoming
    if shows.any?
      shows.first.start.strftime('%B %d, %Y')
    end
  end

  def this_year?
    start.year == Date.today.year
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  geocoded_by :location
  after_validation :geocode

  def self.this_year
    Timeslot.this_year.collect { |t| t.venue }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_page_title

  private

  def set_page_title
    @page = Page.new title: self.class.to_s.gsub('Controller', '')
  end
end

app/controllers/pages_controller.rb
class PagesController < Petrie::PagesController

	layout 'application'

  def home
    super
  end

  # def show
  #   super
  # end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    @sponsors = Sponsor.this_year

    @platinum_sponsors = Sponsor.level('platinum').this_year
    @gold_sponsors     = Sponsor.level('gold').this_year
    @silver_sponsors   = Sponsor.level('silver').this_year
    @bronze_sponsors   = Sponsor.level('bronze').this_year
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  def index
    @page = Page.new title: 'Schedule', subtitle: Timeslot.first_show_time
    @timeslots = Timeslot.upcoming
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_venue(venue, options = {})
    link_to_map venue.name, venue, options
  end

  def link_to_map(string, resource, options = {})
    defaults = {
      target: '_blank'
    }
    link_to string, map_link(resource.location.squish), defaults.merge(options)
  end

  def map_link(location)
    "http://maps.google.com/?q=#{location}"
  end

  def artists_count
    Artist.this_year.count
  end

  def venues_count
    Venue.this_year.count
  end

  def convert_to_url(string)
    if /^http/ =~ string
      valid_url = string
    else
      valid_url = "http://#{string}"
    end

    valid_url
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper

  def platinum_sponsors
    Sponsor.level('platinum').this_year
  end

  def gold_sponsors
    Sponsor.level('gold').this_year
  end

  def silver_sponsors
    Sponsor.level('silver').this_year
  end

  def bronze_sponsors
    Sponsor.level('bronze').this_year
  end

end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
  def timeslot_past(start)
    'past' if Time.now > start
  end

  def coords(timeslot)
    venue = timeslot.venue
    return unless venue.latitude and venue.longitude
    [venue.latitude, venue.longitude].join(',')
  end
end

app/views/admin/pages/_form.html.erb
<%= semantic_form_for [:admin, @page] do |f| %>
  <%= f.inputs "Details" do %>
    <%= f.input :title %>
    <%= f.input :parent_id, as: :select,
            collection: nested_set_options(resource_class, resource) { |i|
              "#{'&mdash;' * i.level} #{i.title}".html_safe
            } %>
  <% end %>

  <%= f.inputs "Content" do %>
    <div class="medium-editable" data-for="#page_body"></div>
    <%= f.input :body, label: false, input_html: {
        class: 'hidden'
      } %>
  <% end %>

  <%= f.actions %>
<% end %>

app/views/admin/pages/_tree.html.erb
<ol class="sortable-tree"
    data-max-levels="3"
    data-rebuild-url="<%= rebuild_admin_pages_url %>">
  <%= sortable_tree @resource %>
</ol>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row sponsors-logos">
    <p class="lead text-center">
      Tour De Fun <%= Date.today.year %> is sponsored by
    </p>

    <% platinum_sponsors.each do |sponsor| %>
      <div class="col-sm-6 text-center">
        <%= link_to_unless sponsor.website.blank?,
              image_tag(sponsor.logo.url(@page.home? ? :medium_inverted : :medium),
              alt: sponsor.name,
              class: 'img-responsive center-block'),
              convert_to_url(sponsor.website)
          %>
    </div>
      <% end %>
  </div>

  <div id="copyright" class="row">
    <div class="col-sm-12">
      <p>
        &copy; <%= Date.today.year %> Tour de Fun. Made with all the love in the world by <a href="http://twitter.com/nicinabox">@nicinabox</a> and <a href="http://twitter.com/njbiddle">@njbiddle</a>.
      </p>
      <p>
      Images by <a href="http://30mileswest.com/">Ryan Green Photography</a>
      </p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="primary-nav" class="hidden-xs">
  <nav class="nav-left col-sm-5 text-right">
    <a href="/about">About</a>
    <a href="/schedule">Schedule</a>
  </nav>

  <a href="/" id="logo" class="col-sm-2">
    <%= image_tag "tdflogo-white.png", :alt => "TOUR DE FUN", :class => 'img-responsive' %>
  </a>

  <nav class="nav-right col-sm-5">
    <a href="/sponsors">Sponsors</a>
    <a href="/contact">Contact</a>
  </nav>
</div>

<nav class="navbar navbar-transparent visible-xs" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-nav-mobile">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "tdflogo-white.png", :alt => "TOUR DE FUN", :class => 'img-responsive' %>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="primary-nav-mobile">
      <ul class="nav navbar-nav">
        <li>
          <a href="/schedule">Schedule</a>
        </li>
        <li>
          <a href="/about">About</a>
        </li>
        <li>
          <a href="/sponsors">Sponsors</a>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="Tour de Fun" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://tourdefun.net/" />
  <meta property="og:image" content="http://s3.amazonaws.com/tourdefun/logo/logo.png" />
  <meta property="og:image:width" content="800" />
  <meta property="og:image:height" content="800" />


  <title>Tour de Fun</title>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'shared/analytics' %>
</head>
<body class="<%= action_name %>" id="<%= controller_name %>">

  <div id="root">
    <div id="header">
      <%= render 'layouts/header' %>
    </div>

    <div id="main">
      <%= render 'shared/page_title' %>
      <%= yield %>
    </div>

    <div id="root_footer"></div>
  </div>

  <div id="footer">
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="bg-image"></div>

<div class="container">
    <div id="hero">
      <div class="col-sm-12 text-center">
        <h1 class="pacifico">
          <span style="letter-spacing:-.14em">T</span>our De Fun
        </h1>
        <h2>
          <%= Timeslot.first_show_time %>
        </h2>
        <h2>
          Bike centric music and arts festival
        </h2>

        <div class="tagline">
          <%= link_to timeslots_path do %>
            Together we do fun things. Let's do fun things, together.
          <% end %>
        </div>
        
        <div class="row">
          <div class="col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3">
            <a href="http://www.eventbrite.com/e/tour-de-fun-2015-tickets-16267717180?ref=ebtn" target="_blank" class="btn btn-success btn-sm btn-block">Order tickets here!
            </a>
          </div>
          <% if false %>
            <div class="col-sm-3 col-xs-6">
              <a href="https://s3.amazonaws.com/tourdefun/map/TDFMAP.pdf" class="btn btn-success btn-sm btn-block">
                Download the Map!
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%=raw @page.body %>
    </div>
  </div>
</div>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-29039579-1', 'tourdefun.net');
  ga('send', 'pageview');

</script>

<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '532dbec1e32bb466850003cd');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>

app/views/shared/_masthead.html.erb
<% if @page and not @page.home? %>
  <div id="masthead">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h1 class="text-center"><%= @page.title %></h1>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<% if @page and not @page.home? %>
  <div id="page-title" class="text-center">
    <h1 class="pacifico">
      <%= @page.title %>
    </h1>
    <h4><%= @page.try(:subtitle) %></h4>
  </div>
<% end %>

app/views/sir-trevor/_heading_block.html.erb
<div class="content-block heading-block">
  <h2><%= sir_trevor_markdown block["text"] %></h2>
</div>

app/views/sir-trevor/blocks/_heading_block.html.erb
<div class="content-block heading-block">
  <h2><%= sir_trevor_markdown block["text"] %></h2>
</div>

app/views/sir-trevor/blocks/_list_block.html.erb
<div class="content-block ul-block">
  <%= sir_trevor_markdown block["text"] %>
</div>

app/views/sponsors/_bronze_sponsor.erb
<div class="col-sm-2 col-xs-4">
  <div class="bronze-sponsor">
    <% if bronze_sponsor.website.blank? %>
      <%= image_tag bronze_sponsor.logo_url(:medium) %>

    <% else %>
      <%= link_to convert_to_url(bronze_sponsor.website) do %>
        <%= image_tag bronze_sponsor.logo_url(:medium) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sponsors/_gold_sponsor.erb
<div class="col-sm-12">
  <div class="gold-sponsor">
    <% if gold_sponsor.website.blank? %>
      <%= image_tag gold_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>

    <% else %>
      <%= link_to convert_to_url(gold_sponsor.website) do %>
        <%= image_tag gold_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sponsors/_platinum_sponsor.erb
<div class="col-sm-6">
  <div class="platinum-sponsor">
    <% if platinum_sponsor.website.blank? %>
      <%= image_tag platinum_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>

    <% else %>
      <%= link_to convert_to_url(platinum_sponsor.website) do %>
        <%= image_tag platinum_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sponsors/_silver_sponsor.erb
<div class="col-sm-2">
  <div class="silver-sponsor">
    <% if silver_sponsor.website.blank? %>
      <%= image_tag silver_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>

    <% else %>
      <%= link_to convert_to_url(silver_sponsor.website) do %>
        <%= image_tag silver_sponsor.logo_url(:medium),
            class: 'img-responsive center-block' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sponsors/index.html.erb
<div class="container">
  <div class="row">
    <div class="platinum-sponsors sponsors-logos">
      <h4 class="group-title">
        Platinum Sponsors
      </h4>
      <%= render partial: 'platinum_sponsor',
                 collection: @platinum_sponsors %>
    </div>

    <% if @gold_sponsors.any? %>
      <div class="gold-sponsors sponsors-logos">
        <h4 class="group-title">
          Gold Sponsors
        </h4>
        <%= render partial: 'gold_sponsor',
                   collection: @gold_sponsors %>
      </div>
    <% end %>
    
    <% if @silver_sponsors.any? %>
      <div class="silver-sponsors sponsors-logos">
        <h4 class="group-title">
          Silver Sponsors
        </h4>
        <%= render partial: 'silver_sponsor',
                   collection: @silver_sponsors %>
      </div>
    <% end %>

    <% if @bronze_sponsors.any? %>
      <div class="bronze-sponsors sponsors-logos">
        <h4 class="group-title">
          Bronze Sponsors
        </h4>
        <%= render partial: 'bronze_sponsor',
                   collection: @bronze_sponsors %>
      </div>
    <% end %>
  </div>
</div>

app/views/timeslots/_timeslot.html.erb
<%= div_for timeslot, class: "row", data: { location: "#{coords(timeslot)}" } do %>
  <header class="col-sm-12">
    <h3>
      <%= link_to_map "<i class='fa fa-map-marker fa-fw'></i>".html_safe, timeslot.venue %>
      <%= timeslot.venue.name %>
    </h3>
  </header>

  <div class="col-sm-8">
    <% if timeslot.artists.any? %>
      <div class="text-muted timeslot-description">
        <%= simple_format timeslot.description %>
      </div>

      <%=raw timeslot.artists.map { |a|
            link_to_unless a.website.blank?,
              a.name, a.website
          }.to_sentence %>
    <% else %>
      <p class="text-muted">
        No artists scheduled for this time
      </p>
    <% end %>
  </div>

<% end %>

app/views/timeslots/index.html.erb
<div class="container">
  <nav class="centered-tabs">
    <a href="#shows" class="active">Shows</a>
    <a href="#map">Map</a>
  </nav>

    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3">
        <br><a href="http://www.eventbrite.com/e/tour-de-fun-2015-tickets-16267717180?ref=ebtn" target="_blank" class="btn btn-success btn-sm btn-block">Order tickets here!
        </a>
      </div>
    </div>

  <div class="tab-content">
    <div class="tab-pane active row" id="shows">
      <div class="col-sm-10 col-sm-offset-1">

        <% @timeslots.group_by(&:start).each do |start, timeslots| %>
          <div class="timesection <%= timeslot_past(start) %>">
            <h2 id="<%= start.strftime('%l:%M%P').strip %>">
              <strong><%= start.strftime('%l:%M%P') %></strong>
            </h2>

            <%= render timeslots %>
          </div>
        <% end %>


        <% if @timeslots.blank? %>
          <h4 class="text-muted">
            Coming soon!
          </h4>
        <% end %>
      </div>
    </div>

    <div class="tab-pane row" id="map">
      <div class="col-sm-12">
        <div id="map-canvas"></div>
      </div>
    </div>
  </div>
</div>